package Delivery;

import java.util.ArrayList;
import java.util.List;

import Stock.Item;
import Stock.Stock;

/**
 * This class processes an inventory into a manifest (A collection of trucks.)
 * It does this by optimising manifests for capital expenditure by minimizing the quantity of low temperature 
 * trucks through an optimal logistical allocation of items.
 * 
 * @author Greyden Scott
 *
 */

public class Manifest {
	
	List<Truck> fleet;
	
	Stock storeInventory;
	
	Stock coldItems = new Stock();
	Stock ordinaryItems = new Stock();
	
	Stock cargo = new Stock();
	
	/**
	 * Constructs the manifest based on the inventory of items passed through
	 * 
	 * @param storeInventory A Stock of all items to be loaded on to the trucks
	 */
	
	public Manifest(Stock storeInventory) {
		
		this.storeInventory = storeInventory;
		this.fleet = new ArrayList<>();
		boolean fillingUpTruck = false;

		this.storeInventory.sort();
		//this.storeInventory.sortAlpha();
		
		for (Item item : storeInventory.inventory()) {
			if(item.getStorageTemp() <= 10) {
				coldItems.addItem(item);	
			} else {
				ordinaryItems.addItem(item);	
			}
		}
		
		for (Item item : coldItems.inventory()) {
			cargo.addItem(item);
			if (cargo.total() == 800) {
				Truck coldTruck = new RefrigeratedTruck(cargo);
				fleet.add(coldTruck);
				cargo = new Stock();
			}
		}
		
		if (cargo.total() != 800) {
			fillingUpTruck = true;
			for (Item item : ordinaryItems.inventory()) {
			
				if (fillingUpTruck) {
					cargo.addItem(item);
					if (cargo.total() == 800) {
						Truck coldTruck = new RefrigeratedTruck(cargo);
						fleet.add(coldTruck);
						cargo = new Stock();
						fillingUpTruck = false;
					}
				} else {
					cargo.addItem(item);
					if (cargo.total() == 1000) {
						Truck ordinaryTruck = new OrdinaryTruck(cargo);
						fleet.add(ordinaryTruck);
						cargo = new Stock();
					}
				}
			}
		}
		
		if (cargo.total() != 1000) {
			Truck ordinaryTruck = new OrdinaryTruck(cargo);
			fleet.add(ordinaryTruck);
		}

	}
	
	/**
	 * Returns the fleet generated by the constructor
	 * 
	 * 
	 * @return List of Trucks generated by the constructor.
	 */
	public List<Truck> getFleet() {
		return this.fleet;
	}

}
